/**
 * Which recordings each game plays.
 *
 * ## Why this is per game and not one set for the app
 *
 * All twenty-three slots shared one synthesised sound palette, and that was the
 * single largest reason they still felt like one machine after the art, the
 * grids, the cabinets and the bonuses had all been made different. A player does
 * not experience a slot as a paytable — they experience a rhythm, and the sound
 * IS the rhythm. Two games that look different and sound identical are one game.
 *
 * So the assignment is per GAME, like the symbols and the cabinets, and it is
 * written out rather than derived from a hash of the id: a table can be read,
 * argued with and corrected, and "why does Frost Peak sound like that" has an
 * answer somebody chose.
 *
 * ## What is actually in the library
 *
 * Twenty-six usable files, generated by the founder: four reel spins, four
 * lever pulls, six wins, eight jackpot fanfares from two to seven seconds, and
 * four roulette sounds. See `audio/README.md` for every file's measured length
 * and level.
 *
 * That is enough to give each game a distinct COMBINATION but not a distinct
 * file for every slot — with four spin recordings across twenty-three games,
 * some sharing is arithmetic rather than laziness. The sets below are arranged
 * so that games sharing a spin do not also share a win, and so that neighbours
 * in the lobby never sound the same.
 *
 * ## What is deliberately still synthesised
 *
 * Reel stops, the counter tick, taps and the anticipation riser. Those fire at
 * exact instants — five reel stops a spin, a dozen ticks a second during a
 * roll-up — and a recording has an attack delay and a file to fetch first. The
 * library also has none of them. `sound.ts` falls back automatically, so the
 * mechanics stay tight and the moments get the recordings.
 */

import type { SoundSet } from '../sound';

const A = '/audio';

/** Wins, shortest to longest. */
const WIN = [`${A}/win-2.mp3`, `${A}/win-3.mp3`, `${A}/win-4.mp3`, `${A}/win-5.mp3`, `${A}/win-6.mp3`];
/**
 * Jackpot fanfares.
 *
 * Split by length rather than by number, because the two uses are different: a
 * "big win" lands under a rolling counter and has to be over before it ends,
 * while a "mega" is the moment itself and can run. Measured lengths are in
 * `audio/README.md` — 1 and 4 are the two-second renders, 2 and 3 are ~3.8s,
 * and 5 through 8 run to seven.
 */
const BIG = [`${A}/megawin-1.mp3`, `${A}/megawin-4.mp3`, `${A}/megawin-2.mp3`, `${A}/megawin-3.mp3`];
const MEGA = [`${A}/megawin-5.mp3`, `${A}/megawin-6.mp3`, `${A}/megawin-7.mp3`, `${A}/megawin-8.mp3`];
const SPIN = [
  `${A}/reel-spin-1.mp3`,
  `${A}/reel-spin-2.mp3`,
  `${A}/reel-spin-3.mp3`,
  `${A}/reel-spin-4.mp3`,
];
const LEVER = [`${A}/lever-1.mp3`, `${A}/lever-2.mp3`, `${A}/lever-3.mp3`, `${A}/lever-4.mp3`];

/** Build a set from indices, so the table below reads as a grid. */
function set(spin: number, win: number, big: number, mega: number, lever?: number): SoundSet {
  return {
    spin: SPIN[spin % SPIN.length]!,
    win: WIN[win % WIN.length]!,
    big: BIG[big % BIG.length]!,
    mega: MEGA[mega % MEGA.length]!,
    // The bonus announcement borrows the game's own big-win fanfare rather than
    // a shared sting, so a bonus sounds like THIS machine getting excited.
    bonus: BIG[big % BIG.length]!,
    ...(lever === undefined ? {} : { lever: LEVER[lever % LEVER.length]! }),
  };
}

/**
 * The table.
 *
 * Read down a column and no two adjacent games share a value; read across and
 * every row is a combination that appears once. The lever games are the four
 * with a handle — see `api/cabinets`.
 */
export const SOUND_SETS: Record<string, SoundSet> = {
  //                              spin win big mega lever
  'juwa-classic-slots': set(0, 0, 0, 0, 0),
  'slot-emerald-nights': set(1, 1, 1, 1),
  'slot-royal-flush': set(2, 2, 2, 2),
  'slot-ocean-drift': set(3, 3, 3, 3),
  'slot-sunset-strip': set(0, 4, 1, 2),
  'slot-midnight-gold': set(1, 0, 2, 3),
  'slot-neon-alley': set(2, 1, 3, 0),
  'slot-desert-mirage': set(3, 2, 0, 1),
  'slot-frost-peak': set(0, 3, 1, 3),
  'slot-jade-temple': set(1, 4, 2, 0),
  'slot-carnival-row': set(2, 0, 3, 1),
  'slot-jungle-run': set(3, 1, 0, 2),
  'slot-city-lights': set(0, 2, 2, 1),
  'slot-spice-market': set(1, 3, 3, 2),
  'slot-aurora-borealis': set(2, 4, 0, 3),
  'slot-dragons-hoard': set(3, 0, 1, 0),
  'slot-vault-breaker': set(0, 1, 3, 3),
  'slot-supernova': set(1, 2, 0, 0),
  'slot-pharaohs-vault': set(2, 3, 1, 1),
  'slot-storm-chaser': set(3, 4, 2, 2),
  'slot-lucky-sevens': set(0, 0, 3, 0, 1),
  'slot-triple-bar': set(1, 1, 0, 1, 2),
  'slot-fruit-stand': set(2, 2, 1, 2, 3),
};

/**
 * Roulette, which is not a slot and shares nothing with them.
 *
 * The four roulette recordings are the only ones in the library that name a
 * specific game, and using them anywhere else would be worse than using
 * nothing: a ball rattling into a pocket underneath a reel spin is a sound
 * from a different table.
 */
export const ROULETTE_SOUNDS = {
  wheel: `${A}/roulette-wheel.mp3`,
  ball: `${A}/roulette-ball-roll.mp3`,
  drop: `${A}/roulette-ball-drop.mp3`,
  win: `${A}/roulette-win.mp3`,
} as const;

/** Every file, for the service worker and for a warm cache on the lobby. */
export const ALL_SOUND_FILES: string[] = [
  ...new Set([
    ...SPIN,
    ...LEVER,
    ...WIN,
    ...BIG,
    ...MEGA,
    ...Object.values(ROULETTE_SOUNDS),
  ]),
];

export function soundSetFor(gameId: string): SoundSet {
  // A game with no entry gets the classic set rather than silence — a new theme
  // should be playable the moment it is added to the catalogue.
  return SOUND_SETS[gameId] ?? SOUND_SETS['juwa-classic-slots']!;
}
