/**
 * Which recordings each game plays.
 *
 * ## Why this is per game and not one set for the app
 *
 * All twenty-three slots shared one synthesised sound palette, and that was the
 * single largest reason they still felt like one machine after the art, the
 * grids, the cabinets and the bonuses had all been made different. A player does
 * not experience a slot as a paytable — they experience a rhythm, and the sound
 * IS the rhythm. Two games that look different and sound identical are one game.
 *
 * So the assignment is per GAME, like the symbols and the cabinets, and it is
 * written out rather than derived from a hash of the id: a table can be read,
 * argued with and corrected, and "why does Frost Peak sound like that" has an
 * answer somebody chose.
 *
 * ## What is actually in the library
 *
 * Eighty-six files, generated by the founder in two batches: reel spins and
 * stops, lever pulls, wins, jackpot fanfares, an anticipation riser, scatter,
 * coin-lock, cascade, near-miss, taps, ticks, four roulette sounds, and
 * twenty-four thirty-second music beds — four for each of six theme families.
 *
 * Three uploads are discarded rather than used: `reel-stop-5` and `cascade-2`
 * are byte-identical duplicates of their siblings, and `near-miss-4` decodes at
 * a peak of 0.046, which is silence with a filename.
 *
 * That is enough to give each game a distinct COMBINATION but not a distinct
 * file for every slot — with four spin recordings across twenty-three games,
 * some sharing is arithmetic rather than laziness. The sets below are arranged
 * so that games sharing a spin do not also share a win, and so that neighbours
 * in the lobby never sound the same.
 *
 * ## The mechanical layer is shared on purpose
 *
 * Reel stops, taps and the counter tick are the same across all twenty-three.
 * A reel stop is the sound of the machine's MECHANISM, and the mechanism does
 * not change between themes — five different click recordings across the
 * catalogue would read as five different qualities of build, not as five
 * different games. What makes a game its own is its music, its spin and its
 * fanfare, and those are all varied below.
 *
 * Everything still falls back to the synthesised version when a file has not
 * loaded, so a slow network makes the game sound thinner rather than silent.
 */

import type { SoundSet } from '../sound';

const A = '/audio';

/** Wins, shortest to longest. */
const WIN = [`${A}/win-2.mp3`, `${A}/win-3.mp3`, `${A}/win-4.mp3`, `${A}/win-5.mp3`, `${A}/win-6.mp3`];
/**
 * Jackpot fanfares.
 *
 * Split by length rather than by number, because the two uses are different: a
 * "big win" lands under a rolling counter and has to be over before it ends,
 * while a "mega" is the moment itself and can run. Measured lengths are in
 * `audio/README.md` — 1 and 4 are the two-second renders, 2 and 3 are ~3.8s,
 * and 5 through 8 run to seven.
 */
const BIG = [`${A}/megawin-1.mp3`, `${A}/megawin-4.mp3`, `${A}/megawin-2.mp3`, `${A}/megawin-3.mp3`];
const MEGA = [`${A}/megawin-5.mp3`, `${A}/megawin-6.mp3`, `${A}/megawin-7.mp3`, `${A}/megawin-8.mp3`];
const SPIN = [
  `${A}/reel-spin-1.mp3`,
  `${A}/reel-spin-2.mp3`,
  `${A}/reel-spin-3.mp3`,
  `${A}/reel-spin-4.mp3`,
];
const LEVER = [`${A}/lever-1.mp3`, `${A}/lever-2.mp3`, `${A}/lever-3.mp3`, `${A}/lever-4.mp3`];

/*
 * The mechanical layer, shared by every game.
 *
 * Deliberately NOT varied per game, unlike everything above. A reel stop is the
 * sound of the machine's mechanism, and the mechanism is the same mechanism —
 * five different click recordings across the catalogue would read as five
 * different qualities of build rather than as five different games. What makes
 * a game its own is its music, its spin and its fanfare.
 *
 * `reel-stop-5` is a byte-identical duplicate of `reel-stop-1` and is left out,
 * so the five reels cycle four genuinely different clicks. `cascade-2` is a
 * duplicate of `cascade-1`, likewise.
 */
const STOPS = [
  `${A}/reel-stop-1.mp3`,
  `${A}/reel-stop-2.mp3`,
  `${A}/reel-stop-3.mp3`,
  `${A}/reel-stop-4.mp3`,
];
const TAP = `${A}/ui-tap-2.mp3`;
const TICK = `${A}/coin-tick-3.mp3`;
const SCATTER = `${A}/scatter-land-1.mp3`;
const COIN_LOCK = `${A}/coin-lock-2.mp3`;
const CASCADE = `${A}/cascade-1.mp3`;
/*
 * `near-miss-4` is discarded: it decodes at a peak of 0.046, which is silence
 * with a number attached. The other three are real.
 */
const NEAR_MISS = `${A}/near-miss-2.mp3`;
const TENSION = [
  `${A}/anticipation-1.mp3`,
  `${A}/anticipation-2.mp3`,
  `${A}/anticipation-3.mp3`,
  `${A}/anticipation-4.mp3`,
];
const TRIGGER = [
  `${A}/bonus-trigger-1.mp3`,
  `${A}/bonus-trigger-2.mp3`,
  `${A}/bonus-trigger-3.mp3`,
];

/**
 * The music, by theme family.
 *
 * Four thirty-second beds per family, so two games sharing a family still do
 * not share a bed — which is the whole reason there are four. Thirty seconds
 * rather than sixty because that is what the free tier renders; they loop, and
 * a bed nobody is listening to closely loops fine at thirty.
 *
 * Which family a game belongs to is written out below rather than derived from
 * its art or its maths, because it is a musical judgement: Ocean Drift and
 * Emerald Nights share nothing except that both want something wide and slow
 * underneath them.
 */
const BEDS: Record<string, string[]> = {
  egypt: [1, 2, 3, 4].map((n) => `${A}/bed-egypt-${n}.mp3`),
  ice: [1, 2, 3, 4].map((n) => `${A}/bed-ice-${n}.mp3`),
  neon: [1, 2, 3, 4].map((n) => `${A}/bed-neon-${n}.mp3`),
  asia: [1, 2, 3, 4].map((n) => `${A}/bed-asia-${n}.mp3`),
  classic: [1, 2, 3, 4].map((n) => `${A}/bed-classic-${n}.mp3`),
  deep: [1, 2, 3, 4].map((n) => `${A}/bed-deep-${n}.mp3`),
};

/** Build a set from indices, so the table below reads as a grid. */
function set(
  bed: string,
  variant: number,
  spin: number,
  win: number,
  big: number,
  mega: number,
  lever?: number,
): SoundSet {
  return {
    bed: BEDS[bed]![variant % 4]!,
    spin: SPIN[spin % SPIN.length]!,
    win: WIN[win % WIN.length]!,
    big: BIG[big % BIG.length]!,
    mega: MEGA[mega % MEGA.length]!,
    // A real trigger sting now, rather than the big-win fanfare it borrowed
    // when there was nothing else: "something is about to happen" and "you
    // won" are different sentences.
    bonus: TRIGGER[big % TRIGGER.length]!,
    tension: TENSION[spin % TENSION.length]!,
    // Shared by every game — see the note on STOPS.
    stops: STOPS,
    tap: TAP,
    tick: TICK,
    scatter: SCATTER,
    nearMiss: NEAR_MISS,
    coinLock: COIN_LOCK,
    cascade: CASCADE,
    ...(lever === undefined ? {} : { lever: LEVER[lever % LEVER.length]! }),
  };
}

/**
 * The table.
 *
 * Read down a column and no two adjacent games share a value; read across and
 * every row is a combination that appears once. The lever games are the four
 * with a handle — see `api/cabinets`.
 */
export const SOUND_SETS: Record<string, SoundSet> = {
  //                          bed family  variant  spin  win  big  mega  lever
  'juwa-classic-slots':   set('classic',  0,       0,    0,   0,   0,    0),
  'slot-lucky-sevens':    set('classic',  1,       0,    0,   3,   0,    1),
  'slot-triple-bar':      set('classic',  2,       1,    1,   0,   1,    2),
  'slot-fruit-stand':     set('classic',  3,       2,    2,   1,   2,    3),

  'slot-desert-mirage':   set('egypt',    0,       3,    2,   0,   1),
  'slot-pharaohs-vault':  set('egypt',    1,       2,    3,   1,   1),
  'slot-spice-market':    set('egypt',    2,       1,    3,   3,   2),
  'slot-vault-breaker':   set('egypt',    3,       0,    1,   3,   3),

  'slot-frost-peak':      set('ice',      0,       0,    3,   1,   3),
  'slot-aurora-borealis': set('ice',      1,       2,    4,   0,   3),
  'slot-city-lights':     set('ice',      2,       0,    2,   2,   1),
  'slot-storm-chaser':    set('ice',      3,       3,    4,   2,   2),

  'slot-neon-alley':      set('neon',     0,       2,    1,   3,   0),
  'slot-carnival-row':    set('neon',     1,       2,    0,   3,   1),
  'slot-sunset-strip':    set('neon',     2,       0,    4,   1,   2),
  'slot-supernova':       set('neon',     3,       1,    2,   0,   0),

  'slot-jade-temple':     set('asia',     0,       1,    4,   2,   0),
  'slot-dragons-hoard':   set('asia',     1,       3,    0,   1,   0),
  'slot-royal-flush':     set('asia',     2,       2,    2,   2,   2),
  'slot-midnight-gold':   set('asia',     3,       1,    0,   2,   3),

  'slot-ocean-drift':     set('deep',     0,       3,    3,   3,   3),
  'slot-emerald-nights':  set('deep',     1,       1,    1,   1,   1),
  'slot-jungle-run':      set('deep',     2,       3,    1,   0,   2),
};

/**
 * Roulette, which is not a slot and shares nothing with them.
 *
 * The four roulette recordings are the only ones in the library that name a
 * specific game, and using them anywhere else would be worse than using
 * nothing: a ball rattling into a pocket underneath a reel spin is a sound
 * from a different table.
 */
export const ROULETTE_SOUNDS = {
  wheel: `${A}/roulette-wheel.mp3`,
  ball: `${A}/roulette-ball-roll.mp3`,
  drop: `${A}/roulette-ball-drop.mp3`,
  win: `${A}/roulette-win.mp3`,
} as const;

/**
 * The five instant games.
 *
 * ## Why they had none
 *
 * `useSoundSet` was built for slot machines and every field on it describes a
 * reel — spin, stops, lever, scatter, near-miss. Crash has no reels, so the
 * instant games never installed a set at all, and `sounds.win()` fell all the
 * way through to its SYNTHESISED fallback: a two-oscillator chime that exists
 * so a game is never silent while its files download.
 *
 * That fallback is a stopgap and it sounded like one. It is a large part of
 * why these five were described as feeling built in the 1990s — every other
 * screen in the app plays a recorded fanfare and these played a beep.
 *
 * ## What they get
 *
 * The mechanical layer (taps, ticks) plus the three win tiers, and nothing
 * else, because there is nothing else: no reel to stop, no lever to pull, no
 * scatter to land. The tick doubles as the peg strike in Plinko and the digit
 * churn in Limbo and Dice, which is the right instrument for both — it is a
 * small hard click, and that is what a ball hitting a pin sounds like.
 *
 * One set across all five: they share a bed and a visual language already, and
 * a win should sound like a win wherever the player is standing.
 */
export const INSTANT_SOUNDS: SoundSet = {
  win: WIN[2]!,
  big: BIG[1]!,
  mega: MEGA[2]!,
  bonus: `${A}/bonus-trigger-2.mp3`,
  coinLock: `${A}/coin-lock-2.mp3`,
  tick: `${A}/coin-tick-2.mp3`,
  tap: `${A}/ui-tap-1.mp3`,
};

/** Every file, for the service worker and for a warm cache on the lobby. */
export const ALL_SOUND_FILES: string[] = [
  ...new Set([
    ...SPIN,
    ...LEVER,
    ...WIN,
    ...BIG,
    ...MEGA,
    ...Object.values(ROULETTE_SOUNDS),
    ...(Object.values(INSTANT_SOUNDS).filter((v) => typeof v === 'string') as string[]),
  ]),
];

export function soundSetFor(gameId: string): SoundSet {
  // A game with no entry gets the classic set rather than silence — a new theme
  // should be playable the moment it is added to the catalogue.
  return SOUND_SETS[gameId] ?? SOUND_SETS['juwa-classic-slots']!;
}
